#pragma once



//#define DEBUG_1_ENABLE
//#define DEBUG_2_ENABLE
#define DEBUG_3_ENABLE

#define DEBUG_SERIAL Serial
#define DEBUG_SERIAL_EVENT serialEvent

#define CONFIG_NETWORK 1
#define CONFIG_HTTP_SERVER 1
#define CONFIG_LOGGER 1
#define CONFIG_TELNET_SERVER 1
#define CONFIG_WORKER_PROCESS 1
#define CONFIG_NODE_SCAN_TASK 1

#define CONFIG_SENSORS 0
#define CONFIG_SENSOR_HUB 0
#define CONFIG_SENSORS_JSON_OUTPUT 0
#define CONFIG_SYSTEM_STATUS_SENSOR 0
#define CONFIG_SENSOR_STATE_SERVLET 0

#define OUTPUT_QUEUE_SIZE 140
#define COMM_SERIAL Serial1
#define COMM_SERIAL_EVENT serialEvent1

