manifest:
  defaults:
    remote: szkudlik-homeAutomation

  remotes:
    - name: szkudlik-homeAutomation
      url-base: https://github.com/szkudlik-homeAutomation

  projects:
    - name: Common_code
      path: src/Common_code
      repo-path: Common_code.git
      import: 
        path-prefix: LightControl
      revision: 04eef5ce9def4e28cd4f5aedf6a0721460de9037

  self:
      path: LightControl