#include "../global.h"
#include <EEPROM.h>

void SetDefaultEEPromValues()
{
  EEPROM.write(EEPROM_CANNARY_OFFSET,EEPROM_CANNARY);
  
  // device ID is supposed to be pre-set for a node
  
  EEPROM.write(EEPROM_ACTION_TABLE_USAGE_OFFSET,0);

  for (uint8_t i=0; i<NUM_OF_OUTPUTS; i++) 
  {
    EEPROM.write(EEPROM_DEFAULT_TIMER_VALUE_OFFSET+i*(sizeof(uint16_t)),0);
    EEPROM.write(EEPROM_DEFAULT_TIMER_VALUE_OFFSET+i*(sizeof(uint16_t))+1,0); //16bit
  }

#if CONFIG_CENTRAL_NODE

  EEPROM.write(EEPROM_DEVICE_ID_OFFSET,CENTRAL_NODE_DEVICE_ID);
  
  EEPROM.write(EEPROM_IP+0,192);
  EEPROM.write(EEPROM_IP+1,168);
  EEPROM.write(EEPROM_IP+2,101);
  EEPROM.write(EEPROM_IP+3,22);
  EEPROM.write(EEPROM_IPMASK+0,255);
  EEPROM.write(EEPROM_IPMASK+1,255);
  EEPROM.write(EEPROM_IPMASK+2,255);
  EEPROM.write(EEPROM_IPMASK+3,0);
  EEPROM.write(EEPROM_GATEWAY+0,192);
  EEPROM.write(EEPROM_GATEWAY+1,168);
  EEPROM.write(EEPROM_GATEWAY+2,101);
  EEPROM.write(EEPROM_GATEWAY+3,1);
  EEPROM.write(EEPROM_DNS+0,192);
  EEPROM.write(EEPROM_DNS+1,168);
  EEPROM.write(EEPROM_DNS+2,101);
  EEPROM.write(EEPROM_DNS+3,1);
  EEPROM.write(EEPROM_MAC+0,0x18);
  EEPROM.write(EEPROM_MAC+1,0xC0);
  EEPROM.write(EEPROM_MAC+2,0x4D);
  EEPROM.write(EEPROM_MAC+3,0x2A);
  EEPROM.write(EEPROM_MAC+4,0x16);
  EEPROM.write(EEPROM_MAC+5,0x78);

#endif
}
